spring:
  application:
    name: sistema-gestao-pagamento
  datasource:
    url: jdbc:postgresql://${BD_HOST}:${BD_PORT}/${BD_NAME}
    driverClassName: org.postgresql.Driver
    username: ${BD_USERNAME}
    password: ${BD_PASSWORD}
    
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html
    operations-sorter: method
    tags-sorter: alpha
    try-it-out-enabled: true
    enabled: true

server:
  port: 8080


